INPUT_FILE=/shared_silo/scratch/datasets/sft-pipeline-stage3/train.jsonl
OUTPUT_FILE=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference/examples/backlog_inference/data/sft-pipeline-stage3-train.jsonl
DISPATCHER_PORT=9999
SESSION_NAME=dispatcher-server-annotations
WORK_TIMEOUT=180
MAX_RETRIES=5
