INPUT_FILE=/shared_silo/scratch/datasets/rahul-sft-data/math-only/train_sft.jsonl
OUTPUT_FILE=/shared_silo/scratch/adamhrin@amd.com/dispatcher/examples/backlog_inference/data/rahul-sft-math-only-glm52-fp8-tp4.jsonl
DISPATCHER_PORT=10052
SESSION_NAME=dispatcher-server-sft-math-only-glm52-fp8-tp4
WORK_TIMEOUT=5400
MAX_RETRIES=3
