INPUT_FILE=/shared_silo/scratch/rahul.aralikatte@amd.com/sft-data/input-stage5.jsonl
OUTPUT_FILE=/shared_silo/scratch/rahul.aralikatte@amd.com/sft-data/output-stage5-dispatcher-think.jsonl
DISPATCHER_PORT=9999
SESSION_NAME=dispatcher-server-sft-pipeline-stage5
WORK_TIMEOUT=5400
WORKERS=150
MAX_RETRIES=3
