INPUT_FILE=/scratch/project_462001516/datasets/Dolci-Think-SFT-32B-excellent/train-trace-le16k.jsonl
OUTPUT_FILE="${OUTPUT_FILE:-/scratch/project_462001516/users/zosaelai2/dispatcher/examples/backlog_inference/results/Dolci-Think-SFT-32B-excellent-fi.jsonl}"
DISPATCHER_PORT=10014
SESSION_NAME=dispatcher-server-translation-split-traces
WORK_TIMEOUT=10800
MAX_RETRIES=3
SKIP_DISPATCHER_INSTALL=1
