"""Generalized placeholder handling for instruction processing and value generation."""
from typing import Any, Dict, Generator, List, Union, Optional
import re
import json
import random
from dataclasses import dataclass, field

from dispatcher.taskmanager.backend.request import Request, Response
from dispatcher.taskmanager.task.base import TaskFailed
from .utils.error_utils import format_error_type_with_turn


@dataclass
class PlaceholderData:
    """Data class for placeholder information for a specific turn."""
    instruction_ids: List
    instructions: List[str]
    instruction_categories: List[str]
    placeholders_meta: List[Dict]  # Placeholder metadata per instruction
    query: str
    original_instructions: List[str]  # Store originals before modification


class PlaceholderHandler:
    """Generalized placeholder handler for instruction processing and value generation.

    Handles three types of placeholders:
    - static: Values sampled from a predefined lookup table
    - numeric: Random integers within a specified range
    - dynamic: Values generated by LLM based on query context
    """

    def __init__(self,
                 turn_idx: int,
                 instruction_categories: List[str],
                 instructions: List[str],
                 instruction_ids: List,
                 placeholders_meta: List[Dict],
                 query: str,
                 placeholder_lookup: Dict[str, Any]):
        """Initialize with data for a specific turn.

        Args:
            turn_idx: Current turn index
            instruction_categories: Categories for this turn
            instructions: Instructions for this turn (with placeholders)
            instruction_ids: Instruction IDs for this turn
            placeholders_meta: Placeholder metadata per instruction
            query: Query for this turn
            placeholder_lookup: Global lookup table for static placeholder values
        """
        self.turn_idx = turn_idx
        self.placeholder_lookup = placeholder_lookup

        # Store original data
        self.data = PlaceholderData(
            instruction_ids=instruction_ids.copy(),
            instructions=instructions.copy(),
            instruction_categories=instruction_categories.copy(),
            placeholders_meta=placeholders_meta.copy() if placeholders_meta else [{} for _ in instructions],
            query=query,
            original_instructions=instructions.copy()
        )

        # Find instructions that need placeholder processing
        self.instructions_with_placeholders = self._find_instructions_with_placeholders()
        
        # Store generated values (will be populated during processing)
        self.generated_values: Dict[int, Dict[str, Any]] = {}

    def has_placeholders(self) -> bool:
        """Check if any instructions have placeholders that need processing."""
        return len(self.instructions_with_placeholders) > 0

    def _find_instructions_with_placeholders(self) -> List[int]:
        """Find indices of instructions that have placeholders."""
        indices = []
        for idx, instruction in enumerate(self.data.instructions):
            # Check if instruction contains any {placeholder} patterns
            if re.search(r'\{\w+\}', instruction):
                indices.append(idx)
        return indices

    def _get_placeholder_names(self, instruction: str) -> List[str]:
        """Extract placeholder names from an instruction."""
        return re.findall(r'\{(\w+)\}', instruction)

    def _get_placeholder_type(self, name: str, instruction_meta: Dict) -> str:
        """Determine the type of a placeholder."""
        if name in instruction_meta:
            return instruction_meta[name].get('type', 'unknown')
        if name in self.placeholder_lookup:
            return self.placeholder_lookup[name].get('type', 'unknown')
        # Infer from name
        if name in ('N', 'M', 'min_count', 'max_count', 'percentage', 'min_length'):
            return 'numeric'
        if name in ('keywords', 'forbidden_words', 'keyword', 'word', 'phrase', 'end_phrase', 'topic'):
            return 'dynamic'
        return 'unknown'

    def process_static_and_numeric_placeholders(self) -> None:
        """Process static and numeric placeholders (no LLM needed)."""
        for instruction_idx in self.instructions_with_placeholders:
            instruction = self.data.original_instructions[instruction_idx]
            instruction_meta = self.data.placeholders_meta[instruction_idx] if instruction_idx < len(self.data.placeholders_meta) else {}
            
            placeholder_names = self._get_placeholder_names(instruction)
            kwargs = {}
            
            for name in placeholder_names:
                ptype = self._get_placeholder_type(name, instruction_meta)
                
                if ptype == 'static':
                    # Sample from lookup table or instruction-specific values
                    values = []
                    if name in instruction_meta and 'values' in instruction_meta[name]:
                        values = instruction_meta[name]['values']
                    elif name in self.placeholder_lookup and 'values' in self.placeholder_lookup[name]:
                        values = self.placeholder_lookup[name]['values']
                    
                    if values:
                        kwargs[name] = random.choice(values)
                    else:
                        kwargs[name] = f"[{name}]"  # Fallback
                
                elif ptype == 'numeric':
                    # Generate random number within range
                    min_val, max_val = 1, 10  # Defaults
                    if name in instruction_meta:
                        min_val = instruction_meta[name].get('min', min_val)
                        max_val = instruction_meta[name].get('max', max_val)
                    elif name in self.placeholder_lookup:
                        min_val = self.placeholder_lookup[name].get('min', min_val)
                        max_val = self.placeholder_lookup[name].get('max', max_val)
                    
                    kwargs[name] = random.randint(int(min_val), int(max_val))
            
            # Store generated values
            if instruction_idx not in self.generated_values:
                self.generated_values[instruction_idx] = {}
            self.generated_values[instruction_idx].update(kwargs)

    def process_dynamic_placeholders(self, gen_params: Dict[str, Any]) -> Generator[Union[Request, List[Request]], Any, None]:
        """Process dynamic placeholders that require LLM generation."""
        for instruction_idx in self.instructions_with_placeholders:
            instruction = self.data.original_instructions[instruction_idx]
            instruction_meta = self.data.placeholders_meta[instruction_idx] if instruction_idx < len(self.data.placeholders_meta) else {}
            
            placeholder_names = self._get_placeholder_names(instruction)
            
            # Find dynamic placeholders
            dynamic_placeholders = [
                name for name in placeholder_names 
                if self._get_placeholder_type(name, instruction_meta) == 'dynamic'
            ]
            
            if not dynamic_placeholders:
                continue
            
            # Load and format the dynamic placeholder prompt
            prompt_template = self._load_dynamic_placeholder_prompt()
            prompt = prompt_template.format(
                query=self.data.query,
                instruction=instruction,
                placeholders=", ".join(dynamic_placeholders)
            )
            
            # Generate values via LLM
            response: Response = yield Request({
                "messages": [{"role": "user", "content": prompt}],
                **gen_params
            })
            response_text = response.get_text()
            
            # Parse response
            try:
                parsed = self._parse_dynamic_response(response_text)
                kwargs = parsed.get('kwargs', {})
                
                # Store generated values
                if instruction_idx not in self.generated_values:
                    self.generated_values[instruction_idx] = {}
                self.generated_values[instruction_idx].update(kwargs)
                
            except (json.JSONDecodeError, KeyError) as e:
                raise TaskFailed(
                    message=f"Failed to parse dynamic placeholder response at turn {self.turn_idx}, instruction {instruction_idx}: {e}. Response: {response_text}",
                    error_type=format_error_type_with_turn("dynamic_placeholder_generation_failed", self.turn_idx)
                )

    def get_final_instructions(self) -> List[str]:
        """Get instructions with all placeholders replaced with generated values."""
        final_instructions = self.data.original_instructions.copy()
        
        for instruction_idx, kwargs in self.generated_values.items():
            if instruction_idx < len(final_instructions):
                instruction = final_instructions[instruction_idx]
                
                # Replace placeholders with values
                for name, value in kwargs.items():
                    placeholder = "{" + name + "}"
                    if isinstance(value, list):
                        # Format list as quoted, comma-separated
                        formatted = ", ".join(f'"{v}"' for v in value)
                        instruction = instruction.replace(placeholder, formatted)
                    else:
                        instruction = instruction.replace(placeholder, str(value))
                
                final_instructions[instruction_idx] = instruction
        
        return final_instructions

    def get_execution_kwargs(self) -> List[Dict[str, Any]]:
        """Get kwargs for evaluation functions for each instruction.

        Returns:
            List of kwargs dictionaries, one per instruction.
            Empty dict for instructions without placeholders.
        """
        kwargs_list = []
        
        for instruction_idx in range(len(self.data.instructions)):
            if instruction_idx in self.generated_values:
                kwargs_list.append(self.generated_values[instruction_idx].copy())
            else:
                kwargs_list.append({})
        
        return kwargs_list

    def _load_dynamic_placeholder_prompt(self) -> str:
        """Load the dynamic placeholder generation prompt."""
        with open("model_prompts/generate_dynamic_placeholders_prompt.txt", 'r', encoding='utf-8') as f:
            return f.read()

    def _parse_dynamic_response(self, response_text: str) -> Dict[str, Any]:
        """Parse dynamic placeholder generation response."""
        # Try to extract JSON from triple backticks
        backticks_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', response_text, re.DOTALL)
        if backticks_match:
            return json.loads(backticks_match.group(1))
        
        # Fallback: find JSON object
        json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
        if json_match:
            return json.loads(json_match.group())
        
        return json.loads(response_text)
