"""Placeholder resolution for constraint processing.

Provides two concrete resolvers for replacing placeholders in constraint texts:
  - StaticPlaceholderResolver  – values sampled from a lookup table (no LLM)
  - LLMPlaceholderResolver     – numeric and dynamic values generated by an LLM
"""

from typing import Any, Dict, List, Optional
import json
import random
import re

from dispatcher.taskmanager.backend.request import Request


class StaticPlaceholderResolver:
    """Resolve static placeholders from a lookup table.

    Each entry in the lookup is expected to have a ``values`` list from
    which one item is chosen at random.
    """

    def __init__(self, lookup: Dict[str, Any]):
        self.lookup = lookup

    def resolve(self, placeholders: Dict[str, Dict]) -> Dict[str, Any]:
        """Return {name: value} for every static placeholder."""
        resolved = {}
        for name, meta in placeholders.items():
            if meta.get("type") != "static":
                continue
            values = meta.get("values") or self.lookup.get(name, {}).get("values")
            if values:
                resolved[name] = random.choice(values)
            else:
                resolved[name] = f"[{name}]"
        return resolved


class LLMPlaceholderResolver:
    """Resolve numeric and dynamic placeholders in a single LLM call.

    A constraint may contain any mix of numeric (counts, lengths, etc.)
    and dynamic (keywords, phrases, etc.) placeholders. This resolver
    builds one prompt that asks the LLM to generate values for all of
    them at once, so the values are mutually coherent.
    """

    PROMPT_FILE = "model_prompts/generate_placeholders_prompt.txt"

    def __init__(self):
        with open(self.PROMPT_FILE, "r", encoding="utf-8") as f:
            self._prompt_template = f.read()

    def build_request(
        self,
        constraint_id: str,
        constraint_text: str,
        placeholders: Dict[str, Dict],
        query: str,
        gen_params: Dict[str, Any],
    ) -> Optional[Request]:
        """Build a single LLM request for all non-static placeholders.

        Returns None if every placeholder is static (nothing for the LLM to do).
        """
        # Collect non-static placeholders as {name: type}
        llm_placeholders = {
            name: meta.get("type", "dynamic")
            for name, meta in placeholders.items()
            if meta.get("type") != "static"
        }
        if not llm_placeholders:
            return None

        prompt = self._prompt_template.format(
            query=query,
            constraint=constraint_text,
            placeholders=json.dumps(llm_placeholders),
        )
        return Request(
            {"messages": [{"role": "user", "content": prompt}], **gen_params},
            context={"constraint_id": constraint_id},
        )

    def parse_response(self, response_text: str) -> Dict[str, Any]:
        """Parse the LLM JSON response into {placeholder_name: value}."""
        return _extract_json_values(response_text)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _extract_json_values(text: str) -> Dict[str, Any]:
    """Extract a JSON object from LLM output, handling markdown fences."""
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if m:
        return json.loads(m.group(1))
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if m:
        return json.loads(m.group())
    return json.loads(text)


def format_value(value: Any) -> str:
    """Format a resolved placeholder value for insertion into constraint text."""
    if isinstance(value, list):
        return ", ".join(f'"{v}"' for v in value)
    return str(value)
