INPUT_FILE=/shared_silo/scratch/datasets/Llama-Nemotron-Post-Training-Dataset_SFT_math/SFT/math/math_v1.1.jsonl
OUTPUT_FILE=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference/examples/inference/data/Llama-Nemotron-SFT-math-translated-gemma4-fi.jsonl
DISPATCHER_PORT=9998
SESSION_NAME=dispatcher-server-translation
DISPATCHER_PKG=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference
WORK_TIMEOUT=3600
MAX_RETRIES=3
