INPUT_FILE=/shared_silo/scratch/datasets/Llama-Nemotron-Post-Training-Dataset_SFT_math/SFT/math/math_v1.1.jsonl
OUTPUT_FILE=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference/examples/inference/data/sweeps/translation-split-traces.jsonl
DISPATCHER_PORT=10014
SESSION_NAME=dispatcher-server-translation-split-traces
DISPATCHER_PKG=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference
WORK_TIMEOUT=10800
MAX_RETRIES=3
