SERVER_ADDRESS_FILE=.dispatcher-server-annotations
DISPATCHER_PKG=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference
LAUNCHER=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference/examples/inference/tw_singularity_launcher.sh
TASK=tasks.inference_task.InferenceTask
REQUEST_TIMEOUT=600
MAX_MODEL_LEN=32768
GPUS_PER_TASK=1
