SERVER_ADDRESS_FILE=.dispatcher-server-sft-pipeline-stage5
DISPATCHER_PKG=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference
LAUNCHER=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference/examples/inference/tw_singularity_launcher.sh
TASK=tasks.inference_task_think.InferenceTask
MODEL=/shared_silo/scratch/models/gemma-4-31B-it
REQUEST_TIMEOUT=5000
STARTUP_TIMEOUT=20000
MAX_MODEL_LEN=65536
GPUS_PER_TASK=1
WORKERS=128
