SERVER_ADDRESS_FILE=.dispatcher-server-translation
DISPATCHER_PKG=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference
LAUNCHER=/shared_silo/scratch/adamhrin@amd.com/dispatcher_inference/examples/inference/tw_singularity_launcher.sh
TASK=tasks.reasoning_translation_task.ReasoningTranslationTask
LANGUAGE=fi
MODEL=/shared_silo/scratch/models/gemma-4-31B-it
GPUS_PER_TASK=1
WORKERS=128