INPUT_FILE=/shared_silo/scratch/adamhrin@amd.com/dispatcher_test_retry/examples/reasoning_traces/data/Llama-Nemotron-SFT-math-1.5mplus.jsonl
OUTPUT_FILE=/shared_silo/scratch/adamhrin@amd.com/dispatcher_test_retry/examples/reasoning_traces/data/Llama-Nemotron-SFT-math-1.5mplus-translated-dsv3-fi.jsonl
DISPATCHER_PORT=9997
SESSION_NAME=dispatcher-server-test-retry
DISPATCHER_PKG=/shared_silo/scratch/adamhrin@amd.com/dispatcher_test_retry
WORK_TIMEOUT=3600
MAX_RETRIES=5
